int _putchar(char);
char* _memset(char *, char,  unsigned int);
char* _memcpy(char *, char *, unsigned int);
char* _strchr(char *, char);
unsigned int _strspn(char *s, char *accept);
char* _strstr(char *, char *);
void print_diagsums(int *a, int size);
char* _strpbrk(char *s, char *accept);
char *_strstr(char *haystack, char *needle);
void print_chessboard(char (*a)[8]);
void set_string(char **s, char *to);